"""api/routes/export.py — /api/export"""

import json
from datetime import datetime
from fastapi import APIRouter
from fastapi.responses import JSONResponse
from api.dependencies import get_db

router = APIRouter()


@router.get("/mitre")
def export_mitre():
    """
    Generate a MITRE ATT&CK Navigator layer from all detected techniques.
    Save the response JSON and drop it into:
    https://mitre-attack.github.io/attack-navigator/
    """
    conn = get_db()
    try:
        technique_counts: dict[str, int] = {}

        # Count techniques from persistence entry tags
        for table in ("registry_entries", "task_entries", "service_entries"):
            rows = conn.execute(
                f"SELECT techniques FROM {table}"
            ).fetchall()
            for row in rows:
                for t in json.loads(row["techniques"] or "[]"):
                    tid = t.get("id", "")
                    if tid:
                        technique_counts[tid] = technique_counts.get(tid, 0) + 1

        # Count techniques from attack chain nodes
        rows = conn.execute("SELECT chain_json FROM attack_chains").fetchall()
        for row in rows:
            try:
                for node in json.loads(row["chain_json"]):
                    for t in node.get("techniques", []):
                        tid = t.get("id", "")
                        if tid:
                            technique_counts[tid] = technique_counts.get(tid, 0) + 1
            except Exception:
                pass

        techniques = [
            {
                "techniqueID": tid,
                "score":       min(count, 3),
                "color":       {1: "#ffcccc", 2: "#ff6666", 3: "#cc0000"}.get(
                    min(count, 3), "#ff6666"),
                "comment":     f"Detected {count} time(s)",
                "enabled":     True,
            }
            for tid, count in technique_counts.items()
        ]

        layer = {
            "name":        "Persistence-Hunter Findings",
            "versions":    {"attack": "14", "navigator": "4.9", "layer": "4.5"},
            "domain":      "enterprise-attack",
            "description": (
                f"Generated by Persistence-Hunter on "
                f"{datetime.now().strftime('%Y-%m-%d %H:%M')}"
            ),
            "techniques":  techniques,
            "gradient": {
                "colors":   ["#ffcccc", "#cc0000"],
                "minValue": 0,
                "maxValue": 3,
            },
            "legendItems": [
                {"label": "1 detection",   "color": "#ffcccc"},
                {"label": "2 detections",  "color": "#ff6666"},
                {"label": "3+ detections", "color": "#cc0000"},
            ],
            "showTacticRowBackground": True,
            "tacticRowBackground":     "#dddddd",
        }

        # Return with a filename hint so browsers offer "Save As"
        return JSONResponse(
            content=layer,
            headers={
                "Content-Disposition": (
                    f'attachment; filename="persistence-hunter-'
                    f'{datetime.now().strftime("%Y%m%d")}.json"'
                )
            },
        )
    finally:
        conn.close()
